2025-04-01 20:33:00,759 INFO    MainThread:183 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-01 20:33:00,759 INFO    MainThread:183 [wandb_setup.py:_flush():67] Configure stats pid to 183
2025-04-01 20:33:00,759 INFO    MainThread:183 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-04-01 20:33:00,759 INFO    MainThread:183 [wandb_setup.py:_flush():67] Loading settings from /workspace/tfg_hhernandez/scripts/wandb/settings
2025-04-01 20:33:00,759 INFO    MainThread:183 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-01 20:33:00,760 INFO    MainThread:183 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /workspace/tfg_hhernandez/scripts/wandb/run-20250401_203300-dnbnjdov/logs/debug.log
2025-04-01 20:33:00,760 INFO    MainThread:183 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /workspace/tfg_hhernandez/scripts/wandb/run-20250401_203300-dnbnjdov/logs/debug-internal.log
2025-04-01 20:33:00,760 INFO    MainThread:183 [wandb_init.py:init():761] calling init triggers
2025-04-01 20:33:00,761 INFO    MainThread:183 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'seed': 0, 'data': DotMap(annotations_path='/workspace/tfg_hhernandez/annotations', data_path='/dataset/', batch_size=32, workers=1, down_sampling_rate=5, train=['P_03', 'P_04', 'P_05', 'P_06', 'P_09', 'P_10', 'P_12', 'P_13', 'P_14', 'P_18', 'P_19', 'P_20'], val=['P_01', 'P_02', 'P_16', 'P_17'], test=['P_07', 'P_08', 'P_11', 'P_15']), 'video_model': DotMap(block_size=16, name='timesformer', extract_features=True), 'model': DotMap(multimodal=False, fusion_strategy='concat'), 'object_detector': DotMap(max_detected_objects=4, object_recopilation_strategy='lastframe', object_model='GT'), 'classifier': DotMap(hidden_dims=[512], train=True, test=True, train_weights_path=None, test_weights_path='/results/simple_MLP/timesformer2/best_epoch.pt'), 'train_params': DotMap(lr=0.0005, epochs=20, dropout=0.2, weight_decay=0.3, save_every=20), 'save_dir': '/results/simple_MLP/timesformer2', '_wandb': {}}
2025-04-01 20:33:00,761 INFO    MainThread:183 [wandb_init.py:init():784] starting backend
2025-04-01 20:33:00,762 INFO    MainThread:183 [wandb_init.py:init():788] sending inform_init request
2025-04-01 20:33:00,782 INFO    MainThread:183 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-01 20:33:00,782 INFO    MainThread:183 [wandb_init.py:init():803] backend started and connected
2025-04-01 20:33:00,786 INFO    MainThread:183 [wandb_init.py:init():896] updated telemetry
2025-04-01 20:33:00,807 INFO    MainThread:183 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-01 20:33:01,232 INFO    MainThread:183 [wandb_init.py:init():995] starting run threads in backend
2025-04-01 20:33:01,530 INFO    MainThread:183 [wandb_run.py:_console_start():2377] atexit reg
2025-04-01 20:33:01,531 INFO    MainThread:183 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-01 20:33:01,531 INFO    MainThread:183 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-01 20:33:01,532 INFO    MainThread:183 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-01 20:33:01,534 INFO    MainThread:183 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-01 20:33:12,812 WARNING MsgRouterThr:183 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-01 20:33:12,813 INFO    MsgRouterThr:183 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
