P_07
P_08
P_11
P_15
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 54, in main
    accuracy, avg_loss = test_model(config)
  File "/workspace/tfg_hhernandez/utils/evaluate.py", line 58, in test_model
    raise Exception ("no checkpoint found at '{}'".format(config.aggregator.weights_path))
Exception: no checkpoint found at 'None'
