2025-03-24 16:45:38,131 INFO    MainThread:1874 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-24 16:45:38,131 INFO    MainThread:1874 [wandb_setup.py:_flush():67] Configure stats pid to 1874
2025-03-24 16:45:38,131 INFO    MainThread:1874 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-03-24 16:45:38,131 INFO    MainThread:1874 [wandb_setup.py:_flush():67] Loading settings from /workspace/tfg_hhernandez/wandb/settings
2025-03-24 16:45:38,131 INFO    MainThread:1874 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-24 16:45:38,132 INFO    MainThread:1874 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /workspace/tfg_hhernandez/wandb/run-20250324_164538-9oy8emeq/logs/debug.log
2025-03-24 16:45:38,132 INFO    MainThread:1874 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /workspace/tfg_hhernandez/wandb/run-20250324_164538-9oy8emeq/logs/debug-internal.log
2025-03-24 16:45:38,133 INFO    MainThread:1874 [wandb_init.py:init():761] calling init triggers
2025-03-24 16:45:38,133 INFO    MainThread:1874 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'seed': 0, 'data': DotMap(annotations_path='/workspace/tfg_hhernandez/annotations', data_path='/dataset/', batch_size=8, workers=2, down_sampling_rate=5, train=['P_03', 'P_04', 'P_05', 'P_06', 'P_09', 'P_10', 'P_12', 'P_13', 'P_14', 'P_18', 'P_19', 'P_20'], val=['P_01', 'P_02', 'P_16', 'P_17'], test=['P_07', 'P_08', 'P_11', 'P_15']), 'video_model': DotMap(block_size=16, name='timesformer', extract_features=True), 'aggregator': DotMap(hidden_dims=[512], eval=False, train=False, weights_path='None'), 'train_params': DotMap(lr=0.0005, epochs=20, dropout=0.0, weight_decay=0.3, save_every=20), 'save_dir': '/results/simple_MLP/timesformer', '_wandb': {}}
2025-03-24 16:45:38,133 INFO    MainThread:1874 [wandb_init.py:init():784] starting backend
2025-03-24 16:45:38,133 INFO    MainThread:1874 [wandb_init.py:init():788] sending inform_init request
2025-03-24 16:45:38,153 INFO    MainThread:1874 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-24 16:45:38,153 INFO    MainThread:1874 [wandb_init.py:init():803] backend started and connected
2025-03-24 16:45:38,156 INFO    MainThread:1874 [wandb_init.py:init():896] updated telemetry
2025-03-24 16:45:38,181 INFO    MainThread:1874 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-24 16:45:38,525 INFO    MainThread:1874 [wandb_init.py:init():995] starting run threads in backend
2025-03-24 16:45:38,782 INFO    MainThread:1874 [wandb_run.py:_console_start():2377] atexit reg
2025-03-24 16:45:38,783 INFO    MainThread:1874 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-24 16:45:38,783 INFO    MainThread:1874 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-24 16:45:38,783 INFO    MainThread:1874 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-24 16:45:38,786 INFO    MainThread:1874 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-24 16:52:28,207 WARNING MsgRouterThr:1874 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-24 16:52:28,208 INFO    MsgRouterThr:1874 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
